-- Active: 1783493469997@@pgsql25ouj.postgres.database.azure.com@5432
--** 사용자 **--
-- 사용자
DROP TABLE "User";
CREATE TABLE "User" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"email"	TEXT 	NOT NULL UNIQUE,
	"password"	TEXT		NOT NULL,
	"loginCnt"	INT	DEFAULT 0	NOT NULL,
	"createdAt"	timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN "User"."id" IS 'autoincrement';
COMMENT ON COLUMN "User"."loginCnt" IS 'default:0, 최초 로그인 사용자 구분';

-- 프로필
DROP TABLE "Profile";
CREATE TABLE "Profile" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"userId"	INT		NOT NULL,
	"gender"	TEXT		NULL,
	"nickName"	TEXT		NULL,
	"birthDate"	DATE		NULL,
	"height"	REAL		NULL,
	"goalWeight"	REAL		NULL,
	"goalCalorie"	INT		NULL,
	"createdAt"	timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt"	timestamp(3) DEFAULT CURRENT_TIMESTAMP NULL
);

COMMENT ON COLUMN "Profile"."id" IS 'autoincrement';


--** 식사 **--
-- 식사
DROP TABLE "Meal";
CREATE TABLE "Meal" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"userId"	INT		NOT NULL,
	"mealType"	ENUM		NOT NULL,
	"mealDate"	Date		NOT NULL,
	"goalCalorie"	INT		NULL,
	"unitCalorie"	INT		NULL,
	"photoUrl"	TEXT		NULL,
	"mealStatus"	ENUM		NOT NULL,
	"createdAt"	timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt"	timestamp(3) DEFAULT CURRENT_TIMESTAMP NULL
);

COMMENT ON COLUMN "Meal"."id" IS 'autoincrement';
COMMENT ON COLUMN "Meal"."mealType" IS 'breakfast, lunch, dinner';
COMMENT ON COLUMN "Meal"."mealStatus" IS 'default: pending / pending, completed, skipped';

-- 식사 음식 --
DROP TABLE "MealFood";
CREATE TABLE "MealFood" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"mealId"	INT		NOT NULL,
	"FoodName"	TEXT		NOT NULL,
	"calorie"	INT		NOT NULL
);

COMMENT ON COLUMN "MealFood"."id" IS 'autoincrement';


--** 매일관리 **--
-- 체중
DROP TABLE "Weight";
CREATE TABLE "Weight" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"userId"	INT		NOT NULL,
	"weight"	REAL		NOT NULL,
	"weightDate"	DATE		NOT NULL,
	"bmi"	REAL		NULL,
	"createdAt"	timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN "Weight"."id" IS 'autoincrement';

-- 혈당
DROP TABLE "BloodGlucose";
CREATE TABLE "BloodGlucose" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"userId"	INT		NOT NULL,
	"glucose"	INT		NOT NULL,
	"mealType"	"MealType"		NOT NULL,
	"mealTiming"	"MealTiming"		NOT NULL,
	"createdAt"	timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"bgDate"	DATE		NOT NULL
);

COMMENT ON COLUMN "BloodGlucose"."id" IS 'autoincrement';
COMMENT ON COLUMN "BloodGlucose"."mealType" IS 'breakfast,lunch,dinner';
COMMENT ON COLUMN "BloodGlucose"."mealTiming" IS 'before, after';

-- 혈압
DROP TABLE "BloodPressure";
CREATE TABLE "BloodPressure" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"userId"	INT		NOT NULL,
	"systolic"	INT		NOT NULL,
	"diastolic"	INT		NOT NULL,
	"pulse"	INT		NULL,
	"dayPeriod"	"DayPeriod"		NOT NULL,
	"bpDate"	Date		NOT NULL,
	"createdAt"	timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt"	timestamp(3) DEFAULT CURRENT_TIMESTAMP NULL
);

COMMENT ON COLUMN "BloodPressure"."id" IS 'autoincrement';
COMMENT ON COLUMN "BloodPressure"."dayPeriod" IS 'morning, evening';

--** 데일리 쉴드 **--
-- 데일리 쉴드 --
DROP TABLE "DailyShield";
CREATE TABLE "DailyShield" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"userId"	INT		NOT NULL,
	"dailyDate"	TEXT		NOT NULL,
	"feel"	INT		NULL,
	"energy"	INT		NULL,
	"isExercise"	Boolean		NULL,
	"exersiseTime"	TEXT		NULL,
	"exersiseType"	TEXT		NULL,
	"isWater"	Boolean		NULL,
	"waterCup"	INT		NULL,
	"isSupplement"	Boolean		NULL,
	"supplementType"	TEXT		NULL,
	"createdAt"	timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt"	timestamp(3) DEFAULT CURRENT_TIMESTAMP NULL
);

COMMENT ON COLUMN "DailyShield"."id" IS 'autoincrement';
COMMENT ON COLUMN "DailyShield"."feel" IS '1: 힘듦, 2: 별로, 3: 무난, 4:  좋음, 5: 최고';
COMMENT ON COLUMN "DailyShield"."energy" IS '1: 지침,  2: 부족, 3: 충분, 4: 활력';
COMMENT ON COLUMN "DailyShield"."isExercise" IS 'default:false';
COMMENT ON COLUMN "DailyShield"."exersiseTime" IS 'default:30';
COMMENT ON COLUMN "DailyShield"."exersiseType" IS '걷기, 달리기, 등산, 자전거, 수영, 헬스, 크로스핏, 요가, 필라테스, 스트레칭, 홈트레이닝, 구기 스포츠, 댄스, 기타';
COMMENT ON COLUMN "DailyShield"."isWater" IS 'default:false';
COMMENT ON COLUMN "DailyShield"."waterCup" IS 'default:0';
COMMENT ON COLUMN "DailyShield"."isSupplement" IS 'default:false';
COMMENT ON COLUMN "DailyShield"."supplementType" IS '종합비타민, 비타민C, 비타민D, 비타민B군, 오메가3, 프로바이오틱스, 마그네슘, 칼슘, 아연, 철분, 밀크씨슬, 루테인, 코엔자임Q10, 콜라겐, 글루코사민, 홍삼, 프로틴, 커큐민, 엽산, 기타';


--** 검진 **--
-- 검진 결과
DROP TABLE "CheckUp";
CREATE TABLE "CheckUp" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"userId"	INT		NOT NULL,
	"height"	REAL		NULL,
	"weight"	REAL		NULL,
	"waist"	REAL		NULL,
	"bmi"	REAL		NULL,
	"visionLeft"	REAL		NULL,
	"visionRight"	REAL		NULL,
	"hearing"	TEXT		NULL,
	"bp_systolic"	INT		NULL,
	"bp_diastolic"	INT		NULL,
	"urine_protein"	TEXT		NULL,
	"hemoglobin"	REAL		NULL,
	"fbg"	INT		NULL,
	"creatinine"	REAL		NULL,
	"egfr"	INT		NULL,
	"ast"	INT		NULL,
	"alt"	INT		NULL,
	"ygtp"	INT		NULL,
	"year"	INT		NULL,
	"checkUpDate"	DateTime		NOT NULL,
	"isShow"	BOOLEAN		NOT NULL,
	"createdAt"	timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN "CheckUp"."id" IS 'autoincrement';
COMMENT ON COLUMN "CheckUp"."height" IS '신장';
COMMENT ON COLUMN "CheckUp"."weight" IS '체중';
COMMENT ON COLUMN "CheckUp"."waist" IS '허리둘레';
COMMENT ON COLUMN "CheckUp"."bmi" IS 'BMI';
COMMENT ON COLUMN "CheckUp"."visionLeft" IS '시력(좌)';
COMMENT ON COLUMN "CheckUp"."visionRight" IS '시력(우)';
COMMENT ON COLUMN "CheckUp"."hearing" IS '청력(좌/우)';
COMMENT ON COLUMN "CheckUp"."bp_systolic" IS '혈압(수축기)';
COMMENT ON COLUMN "CheckUp"."bp_diastolic" IS '혈압(이완기)';
COMMENT ON COLUMN "CheckUp"."urine_protein" IS '신장기능-요단백';
COMMENT ON COLUMN "CheckUp"."hemoglobin" IS '혈색소';
COMMENT ON COLUMN "CheckUp"."fbg" IS '공복혈당';
COMMENT ON COLUMN "CheckUp"."creatinine" IS '신장기능-혈청크레아티닌';
COMMENT ON COLUMN "CheckUp"."egfr" IS '신장기능-신사구체여과율';
COMMENT ON COLUMN "CheckUp"."ast" IS '간기능-에이에스티';
COMMENT ON COLUMN "CheckUp"."alt" IS '간기능-에이엘티';
COMMENT ON COLUMN "CheckUp"."ygtp" IS '간기능-감미지티피';
COMMENT ON COLUMN "CheckUp"."checkUpDate" IS '검진 날짜';
COMMENT ON COLUMN "CheckUp"."isShow" IS 'default true';

-- 검진 코멘트
DROP TABLE "CheckUpComment";
CREATE TABLE "CheckUpComment" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"checkUpId"	INT		NOT NULL,
	"comment"	TEXT		NOT NULL
);

COMMENT ON COLUMN "CheckUpComment"."id" IS 'autoincrement';

-- 검진 정규화
DROP TABLE "CheckupAssessment";
CREATE TABLE "CheckupAssessment" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"checkUpId"	INT		NOT NULL,
	"waist"	TEXT		NOT NULL,
	"bmi"	TEXT		NOT NULL,
	"bp"	TEXT		NOT NULL,
	"urine_protein"	TEXT		NOT NULL,
	"hemoglobin"	TEXT		NOT NULL,
	"fbg"	TEXT		NOT NULL,
	"creatinine"	TEXT		NOT NULL,
	"egfr"	TEXT		NOT NULL,
	"ast"	TEXT		NOT NULL,
	"alt"	TEXT		NOT NULL,
	"ygtp"	TEXT		NOT NULL
);

COMMENT ON COLUMN "CheckupAssessment"."id" IS 'autoincrement';


--** PK **--
ALTER TABLE "Weight" ADD CONSTRAINT "PK_WEIGHT" PRIMARY KEY ("id");

ALTER TABLE "Profile" ADD CONSTRAINT "PK_PROFILE" PRIMARY KEY ("id");

ALTER TABLE "MealFood" ADD CONSTRAINT "PK_MEALFOOD" PRIMARY KEY ("id");

ALTER TABLE "CheckUpComment" ADD CONSTRAINT "PK_CHECKUPCOMMENT" PRIMARY KEY ("id", "checkUpId");

ALTER TABLE "CheckupAssessment" ADD CONSTRAINT "PK_CHECKUPASSESSMENT" PRIMARY KEY ("id", "checkUpId");

ALTER TABLE "BloodGlucose" ADD CONSTRAINT "PK_BLOODGLUCOSE" PRIMARY KEY ("id");

ALTER TABLE "DailyShield" ADD CONSTRAINT "PK_DAILYSHIELD" PRIMARY KEY ("id");

ALTER TABLE "User" ADD CONSTRAINT "PK_USER" PRIMARY KEY ("id");

ALTER TABLE "Meal" ADD CONSTRAINT "PK_MEAL" PRIMARY KEY ("id");

ALTER TABLE "CheckUp" ADD CONSTRAINT "PK_CHECKUP" PRIMARY KEY ("id");

ALTER TABLE "BloodPressure" ADD CONSTRAINT "PK_BLOODPRESSURE" PRIMARY KEY ("id");

ALTER TABLE "CheckUpComment" ADD CONSTRAINT "FK_CheckUp_TO_CheckUpComment_1" FOREIGN KEY ("checkUpId")
REFERENCES "CheckUp" ("id");

ALTER TABLE "CheckupAssessment" ADD CONSTRAINT "FK_CheckUp_TO_CheckupAssessment_1" FOREIGN KEY ("checkUpId")
REFERENCES "CheckUp" ("id");






--** Unique **--
-- 쥬얼


ALTER TABLE "CheckUp" ADD CONSTRAINT "UK_CHECKUP_USER_YEAR" UNIQUE ("userId", "year");

-- 큐드
ALTER TABLE "Weight" ADD CONSTRAINT "UK_WEIGHT_USER_DATE" UNIQUE ("userId", "weightDate");

ALTER TABLE "BloodPressure" ADD CONSTRAINT "UK_BP_USER_PERIOD_DATE" UNIQUE ("userId","dayPeriod","bpDate");

ALTER TABLE "BloodGlucose" ADD CONSTRAINT "UK_BLOODGLUCOSE_USER_DATE" UNIQUE ("userId","bgDate","mealType","mealTiming")

-- 블링


--** ENUM **--
-- 쥬얼


-- 큐드
CREATE TYPE DayPeriod AS ENUM ('MORNING','EVENING');
CREATE TYPE MealType AS ENUM ('BREAKFAST','LUNCH','DINNER');
CREATE TYPE MealTiming AS ENUM ('BEFORE','AFTER');

-- 블링