name: Trigger auto deployment for linkcare-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ pub1 ]
    paths:
    - '**'
    - '.github/workflows/linkcare-api-AutoDeployTrigger-93765c6a-b282-4fe0-987f-ec35a6a10c17.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.LINKCAREAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LINKCAREAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LINKCAREAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}app/apps/api
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: linkcarebe.azurecr.io
          registryUsername: ${{ secrets.LINKCAREAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LINKCAREAPI_REGISTRY_PASSWORD }}
          containerAppName: linkcare-api
          resourceGroup: rg-linkcare-kr
          imageToBuild: linkcarebe.azurecr.io/linkcare-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


